### ISSUE TITLE
Incorrect source path

### ISSUE THREAD

**Issue by fa2mm** [bluezed/yii2-floatThead#2]
Change, please, url $sourcePath
`@bower/floatThead/dist` -> `@bower/floatthead/dist`
because "vendor/bower-asset" directory has "floatthead" directory (lower case) and I have error:
"The file or directory to be published does not exist: /var/www/html/vendor/bower-asset/floatThead/dist"

https://github.com/bluezed/yii2-floatThead/blob/7a8e463b3b27c5b0eba51fe479e3affa265d78b3/FloatTheadAsset.php#L19

**Comment by bluezed** [comment]
Done
